spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_test?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate # Flyway? ?? ??? ?? validate? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration